### ISSUE TITLE
PyPI release for django 1.10 compatibility

### ISSUE THREAD

**Issue by ad-m** [django/django-formtools#75]
Hello,

I would like about new PyPI releases of django-formtools. Django 1.10 was released. 46b6839fb0063fa10ffb896ce80f7155ca7a9f6e contains fix for django 1.10 compatibility (below are stacktrace without that). 54f1ccca01e1a2d2062ad76af9c559723edd435c proves that django-formtools is django 1.10 compatibile. I think is good to release django-1.10-compatible version of django-formtools.

```
$ python manage.py test feder --keepdb
Using existing test database for alias 'default'...
...................E........................................................................................
======================================================================
ERROR: test_permitted_user (feder.letters.tests.test_view.ReplyPermissionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adas/Devel/feder/feder/letters/tests/test_view.py", line 85, in test_permitted_user
    response = self.client.get(self._get_url())
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/test/client.py", line 529, in get
    **extra)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/test/client.py", line 333, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adas/Devel/feder/feder/letters/views.py", line 94, in __call__
    return method(request)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/formtools/preview.py", line 58, in preview_get
    context_instance=RequestContext(request))
TypeError: render_to_response() got an unexpected keyword argument 'context_instance'

----------------------------------------------------------------------
```

**Comment by clemenbor** [comment]
Is there going to be a release of django-formtools for django 1.10 before April 2017? (the expected end of extended support for Django 1.9)

**Comment by timgraham** [comment]
It seems like this package may be unmaintained (certainly undermaintained anyway). A put out a [call for maintainers](https://groups.google.com/d/topic/django-developers/3L2BzvLCIR4/discussion) to decide its fate.

**Comment by carpincho** [comment]
😢

**Comment by timgraham** [comment]
I'll try to do a release if I can get access to the PyPI record. I pinged the owner (jezdez) in #django-dev about it.

**Comment by timgraham** [comment]
django-formtools 2.0 is available on PyPI.
